In [ ]:

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [ ]:
peliculas = pd.read_csv('/content/movies2.csv')

In [ ]:
peliculas

                              franquicia  presupuesto  ... puntuacion n_votos
0         Father of the Bride Collection          NaN  ...        5.7   173.0
1                                    NaN          NaN  ...        6.7    13.0
2                      Friday Collection    3500000.0  ...        7.0   513.0
3                                    NaN          NaN  ...        6.0   124.0
4                                    NaN   12000000.0  ...        6.5   767.0
...                                  ...          ...  ...        ...     ...
1344     The Ouija Experiment Collection          NaN  ...        3.0    25.0
1345                                 NaN          NaN  ...        5.5     2.0
1346                                 NaN          NaN  ...        5.7     3.0
1347  Texas Chainsaw Massacre Collection          NaN  ...        5.7    62.0
1348                                 NaN          NaN  ...        6.0     1.0

[1349 rows x 16 columns]

In [ ]:
peliculas.shape

(1349, 16)

Seleccionar solo valores numéricos

In [ ]:
datos_numericos = peliculas.select_dtypes(np.number)

In [ ]:
datos_numericos

      presupuesto  popularidad      ventas  duracion  puntuacion  n_votos
0             NaN     8.387519  76578911.0     106.0         5.7    173.0
1             NaN     0.894647    676525.0     106.0         6.7     13.0
2       3500000.0    14.569650  28215918.0      91.0         7.0    513.0
3             NaN     8.963037        32.0      87.0         6.0    124.0
4      12000000.0     9.592265  41205099.0      92.0         6.5    767.0
...           ...          ...         ...       ...         ...      ...
1344          NaN     1.642247         NaN      86.0         3.0     25.0
1345          NaN     0.352816         NaN      11.0         5.5      2.0
1346          NaN     0.110588         NaN      86.0         5.7      3.0
1347          NaN     9.742082         NaN      90.0         5.7     62.0
1348          NaN     0.121946         NaN       0.0         6.0      1.0

[1349 rows x 6 columns]

In [ ]:
datos_numericos = peliculas.select_dtypes(np.number).fillna(0)

In [ ]:
datos_numericos

      presupuesto  popularidad      ventas  duracion  puntuacion  n_votos
0             0.0     8.387519  76578911.0     106.0         5.7    173.0
1             0.0     0.894647    676525.0     106.0         6.7     13.0
2       3500000.0    14.569650  28215918.0      91.0         7.0    513.0
3             0.0     8.963037        32.0      87.0         6.0    124.0
4      12000000.0     9.592265  41205099.0      92.0         6.5    767.0
...           ...          ...         ...       ...         ...      ...
1344          0.0     1.642247         0.0      86.0         3.0     25.0
1345          0.0     0.352816         0.0      11.0         5.5      2.0
1346          0.0     0.110588         0.0      86.0         5.7      3.0
1347          0.0     9.742082         0.0      90.0         5.7     62.0
1348          0.0     0.121946         0.0       0.0         6.0      1.0

[1349 rows x 6 columns]

In [ ]:

objetivo = "ventas"
independientes = datos_numericos.drop(columns=objetivo).columns

In [ ]:

modelo = LinearRegression()
modelo.fit(X=datos_numericos[independientes], y=datos_numericos[objetivo])

LinearRegression()

In [ ]:
peliculas["ventas_prediccion"] = modelo.predict(datos_numericos[independientes])

Agregamos una nueva columna

In [ ]:
peliculas

                              franquicia  ...  ventas_prediccion
0         Father of the Bride Collection  ...       1.350624e+07
1                                    NaN  ...       5.503581e+06
2                      Friday Collection  ...       3.876680e+07
3                                    NaN  ...       9.331852e+06
4                                    NaN  ...       6.737609e+07
...                                  ...  ...                ...
1344     The Ouija Experiment Collection  ...       3.116096e+06
1345                                 NaN  ...      -2.244229e+05
1346                                 NaN  ...       3.565685e+06
1347  Texas Chainsaw Massacre Collection  ...       4.940244e+06
1348                                 NaN  ...      -4.705404e+05

[1349 rows x 17 columns]

In [ ]:
print (peliculas[["ventas", "ventas_prediccion"]].head(10))

        ventas  ventas_prediccion
0   76578911.0       1.350624e+07
1     676525.0       5.503581e+06
2   28215918.0       3.876680e+07
3         32.0       9.331852e+06
4   41205099.0       6.737609e+07
5     209935.0       2.332946e+06
6  185260553.0       6.183622e+07
7  355237933.0       1.746963e+08
8    1275000.0       4.881519e+06
9    3174695.0       9.708975e+06